variables:
  GIT_STRATEGY: clone
  
stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - runner-genesis
# cp -r $CI_PROJECT_DIR/* /var/www/html/genesis-backend/; 
  script:
    - sshpass -p "sygalin@2024" ssh -o StrictHostKeyChecking=no -t root@192.168.0.244 "mkdir -p /var/www/html/genesis-backend; rsync -avz --include='.*' --exclude '.git' --exclude '.gitlab-ci.yml' $CI_PROJECT_DIR/* /var/www/html/genesis-backend/; cd /var/www/html/genesis-backend/; composer update; cp .env.example .env; php artisan key:generate; chown -R apache:apache /var/www/html/genesis-backend/storage; chcon -R -t httpd_sys_rw_content_t storage/; chcon -R -t httpd_sys_rw_content_t /var/www/html/genesis-backend/bootstrap/cache; touch /etc/httpd/conf.d/genesis-backend.conf; echo -e '<VirtualHost *:80>\n\tDocumentRoot /var/www/html\n\tAlias /genesis-backend /var/www/html/genesis-backend/public\n\t<Directory /var/www/html/genesis-backend/public>\n\t\tOptions Indexes FollowSymLinks\n\t\tAllowOverride All\n\t\tRequire all granted\n\t</Directory>\n</VirtualHost>' > /etc/httpd/conf.d/genesis-backend.conf; systemctl restart httpd"

  only:
      - master