stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - my-runner

  script:
    - sshpass -p "sygalin@2024" ssh root@192.168.0.244
    - sshpass -p "sygalin@2024" scp $CI_PROJECT_DIR/info.php /var/www/html/Test/index.php
    - sshpass -p "sygalin@2024" systemctl reload httpd

  only:
      - main