variables:
  GIT_STRATEGY: clone
  
stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - my-runner

  script:
    - sshpass -p "sygalin@2024" ssh -o StrictHostKeyChecking=no -t root@192.168.0.244 "cp $CI_PROJECT_DIR/phpinfo.php /var/www/html/Test/index.php; systemctl reload httpd"

  only:
      - main