stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - composer install
    - php artisan migrate

test:
  stage: test
  script:
    - phpunit

deploy:
  stage: deploy
  script:
    - rsync -avz ./tests/ http://192.168.0.244:80/tests